workflow_show_topic:
    channel: workflow/{id}
    handler:
        callback: 'workflow.topic'
    requirements:
        id:
            pattern: "[0-9]+"

workflow_task_topic:
    channel: workflow/{id}/task/{action}
    handler:
        callback: 'workflow.topic'
    requirements:
        id:
            pattern: "[0-9]+"
        action:
            pattern: "new|create|edit|update|position_update|status_update|delete|connection_create|connection_delete"

workflow_rpc:
    channel: workflow/{method}
    handler:
        callback: 'workflow.rpc'
    requirements:
        method:
            pattern: "[a-z_]+"
